apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy-app
  labels:
    app: autodeploy-app
  namespace: namespace-workflow-1710284253471
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy-app
  template:
    metadata:
      labels:
        app: autodeploy-app
    spec:
      containers:
        - name: autodeploy-app
          image: acrworkflow1710284253471.azurecr.io/image-workflow-1710284253471:latest
          ports:
            - containerPort: 5000