apiVersion: v1
kind: Service
metadata:
  name: autodeploy-app
  namespace: namespace-workflow-1710284253471
spec:
  type: LoadBalancer
  selector:
    app: autodeploy-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000